### ISSUE TITLE
Uncaught Error: `useConfig` must be used within `UseWagmiPlugin`.

### ISSUE THREAD

**Issue by dataexcess** [unicape/use-wagmi#49]
Hello, 
I copied your code of the nuxt example... I have the same use-wagmi.ts plugin file, my infura api key is in my .env file. I have the same app.vue with some added code. However, you don't show how to do a contractWrite ... Whenever I try to execute a contractWrite method I get the " `useConfig` must be used within`UseWagmiPlugin` " error.

Here's my updated app.vue, please help or provide an example with contractWrite/read. Thank you!

```
<template>
    <div>
      <div>
        <button
          v-for="x in connectors"
          :key="x.name"
          :disabled="!x.ready || isReconnecting || connector?.id === x.id"
          @click="() => connect({ connector: x })"
        >
          <span>{{ x.name }}</span>
          <span v-if="!x.ready"> (unsupported)</span>
          <span v-if="isLoading && x.id === pendingConnector?.id">…</span>
        </button>
      </div>
  
      <div>{{ error && error.message }}</div>
  
      <div>
        <span>{{ ensName ?? address }}</span>
        <span v-if="ensName"> ({{ address }})</span>
      </div>
  
      <img v-if="ensAvatar" :src="ensAvatar" width="40" height="40">
  
      <div>
        <button v-if="address" @click="() => disconnect()">Disconnect</button>
        <span v-if="connector?.name">Connected to {{ connector.name }}</span>
        <button @click="mint">Mint</button>
      </div>
    </div>
  </template>
  
  <script lang="ts" setup>
  import { useAccount, useDisconnect, useEnsAvatar, useEnsName, useConnect, usePrepareContractWrite, useContractWrite } from 'use-wagmi'
  
  const { connector, isReconnecting } = useAccount()
  const { connect, connectors, isLoading, error, pendingConnector } = useConnect()
  
  const { address } = useAccount({
    onConnect: (data:any) => console.log('connected', data),
    onDisconnect: () => console.log('disconnected')
  })
  
  const { data: ensName } = useEnsName({
    address,
    chainId: 1
  })
  
  const { data: ensAvatar } = useEnsAvatar({
    name: ensName,
    chainId: 1
  })
  
  const { disconnect } = useDisconnect()

const ABI = [
        {
            "inputs": [
                {
                "internalType": "contract HashCalls",
                "name": "_tokenContract",
                "type": "address"
                },
                {
                "internalType": "address payable",
                "name": "_artistWallet",
                "type": "address"
                }
            ],
            "stateMutability": "nonpayable",
            "type": "constructor"
            },
            {
            "anonymous": false,
            "inputs": [
                {
                "indexed": true,
                "internalType": "address",
                "name": "previousOwner",
                "type": "address"
                },
                {
                "indexed": true,
                "internalType": "address",
                "name": "newOwner",
                "type": "address"
                }
            ],
            "name": "OwnershipTransferred",
            "type": "event"
            },
            {
            "inputs": [],
            "name": "artist",
            "outputs": [
                {
                "internalType": "address payable",
                "name": "",
                "type": "address"
                }
            ],
            "stateMutability": "view",
            "type": "function"
            },
            {
            "inputs": [],
            "name": "buy",
            "outputs": [],
            "stateMutability": "payable",
            "type": "function"
            },
            {
            "inputs": [],
            "name": "owner",
            "outputs": [
                {
                "internalType": "address",
                "name": "",
                "type": "address"
                }
            ],
            "stateMutability": "view",
            "type": "function"
            },
            {
            "inputs": [],
            "name": "paused",
            "outputs": [
                {
                "internalType": "bool",
                "name": "",
                "type": "bool"
                }
            ],
            "stateMutability": "view",
            "type": "function"
            },
            {
            "inputs": [],
            "name": "price",
            "outputs": [
                {
                "internalType": "uint256",
                "name": "",
                "type": "uint256"
                }
            ],
            "stateMutability": "view",
            "type": "function"
            },
            {
            "inputs": [],
            "name": "renounceOwnership",
            "outputs": [],
            "stateMutability": "nonpayable",
            "type": "function"
            },
            {
            "inputs": [],
            "name": "tokenContract",
            "outputs": [
                {
                "internalType": "contract HashCalls",
                "name": "",
                "type": "address"
                }
            ],
            "stateMutability": "view",
            "type": "function"
            },
            {
            "inputs": [
                {
                "internalType": "address",
                "name": "newOwner",
                "type": "address"
                }
            ],
            "name": "transferOwnership",
            "outputs": [],
            "stateMutability": "nonpayable",
            "type": "function"
            },
            {
            "inputs": [
                {
                "internalType": "bool",
                "name": "_paused",
                "type": "bool"
                }
            ],
            "name": "updatePaused",
            "outputs": [],
            "stateMutability": "nonpayable",
            "type": "function"
        }
    ]

    const mint = () => {
        const { config } = usePrepareContractWrite({ 
            address: '0x9C7F78fB4560f5dB11E634cfF8751aF47C5240bF',
            abi: ABI, 
            functionName: 'buy' 
        })
        const { write } = useContractWrite(config)
        write?.()
    }

  </script>
```

**Comment by unicape** [comment]
@dataexcess Please create a runnable program at [stackblitz](https://stackblitz.com/)

**Comment by unicape** [comment]
@dataexcess  Please see [README](https://github.com/unicape/use-wagmi#quick-start) or [example](https://github.com/unicape/use-wagmi/blob/main/examples/vite/src/main.ts)

**Comment by dataexcess** [comment]
The readme does not cover useContractWrite...

Here's the stackblitz:

https://stackblitz.com/edit/nuxt-starter-yod4cu?file=plugins%2Fuse-wagmi.ts

**Comment by unicape** [comment]
> The readme does not cover useContractWrite...
> 
> Here's the stackblitz:
> 
> https://stackblitz.com/edit/nuxt-starter-yod4cu?file=plugins%2Fuse-wagmi.ts

[WriteContract])(https://github.com/unicape/use-wagmi/blob/main/examples/vite/src/components/WriteContract.vue)

**Comment by dataexcess** [comment]
Sorry, here this one works:

https://stackblitz.com/edit/nuxt-starter-b37fl7?file=app.vue

**Comment by unicape** [comment]
@dataexcess Using `Composition` inside `const mint = () => {}` loses scope so can't find wagmi config

**Comment by dataexcess** [comment]
Ahh interesting! thank you for this gotcha :)

I removed the enclosing method and simply writing the code like this:

```
    const { config } = usePrepareContractWrite({ 
        address: '0x9C7F78fB4560f5dB11E634cfF8751aF47C5240bF',
        abi: ABI, 
        functionName: 'buy' 
    })
    const { write:mint } = useContractWrite(config)
```
and in template using 

` <button @click="mint">Mint</button>
`

but now I get this:

```
app.vue:28 Error: address is required
    at Object.mutationFn6 [as mutationFn] (index.js:1337:11)
    at Object.fn (mutation.ts:179:31)
    at run (retryer.ts:147:31)
    at createRetryer (retryer.ts:204:5)
    at executeMutation (mutation.ts:174:22)
    at Mutation.execute (mutation.ts:216:26)
```
﻿

**Comment by unicape** [comment]
@dataexcess Because your `provider` is not available

**Comment by dataexcess** [comment]
I don't understand why would it not be available? I pass my infura api key to the InfuraProvider in the use-wagmi.ts plugin file... should it not work? What's going wrong?

**Comment by dataexcess** [comment]
Ok, I managed to fix it :). I'm not sure what went wrong, but also I forgot to pass the value of the mint method. Thank you for the quick help!

**Comment by johnny274** [comment]
I also had the same error, how did you fix it? @dataexcess

**Comment by unicape** [comment]
> > @dataexcess Using `Composition` inside `const mint = () => {}` loses scope so can't find wagmi config
> > `Composition` must be used in `setup`
> 
> The mint() function is used inside <script setup>, please explain to me why wagmi config scope is lost? @unicape

The context of vue can only be obtained in setup

**Comment by johnny274** [comment]
Thanks for the quick reply. I have a writeContract function written in utils. In a component, onMounted calls the function without error. Is there any way to call it in a function similar to the mint function without losing context?

**Comment by johnny274** [comment]
https://stackblitz.com/edit/nuxt-starter-vwexyw?file=app.vue

**Comment by unicape** [comment]
All you need to do is turn the arrow function into a normal function @johnny274

**Comment by johnny274** [comment]
Do you mean to convert the createTag function in utils/contract into normal function like this:
https://stackblitz.com/edit/nuxt-starter-vwexyw?file=utils%2Fcontract.js
I switched but the error still error: Error: `useConfig` must be used within `UseWagmiPlugin`.

**Comment by unicape** [comment]
Here's an open source project that uses 'use-wagmi@0.x' that we hope can help you https://github.com/TsengMJ/ModuFlow/tree/main/web

**Comment by johnny274** [comment]
Thank you very much, hope the best things will come to you!!!
