### ISSUE TITLE
CORS issues

### ISSUE THREAD

**Issue by dataexcess** [unicape/use-wagmi#54]
Hello!

While my nuxt app is working... I get the data I request from my smart contracts etc, I do get a lot of errors in the console related to CORS. Any idea why this is, and how I can fix it?

thnx

```
Access to fetch at 'https://rpc.sepolia.org/' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
chunk-BVQHDTV7.js:1565     POST https://rpc.sepolia.org/ net::ERR_FAILED
withTimeout.errorInstance.TimeoutError.body.body @ rpc.ts:79
(anonymous) @ withTimeout.ts:30
(anonymous) @ withTimeout.ts:37
withTimeout @ withTimeout.ts:16
http @ rpc.ts:77
fn @ http.ts:95
request @ http.ts:97
withRetry.delay.count.count @ buildRequest.ts:69
attemptRetry @ withRetry.ts:34
(anonymous) @ withRetry.ts:45
withRetry @ withRetry.ts:24
(anonymous) @ buildRequest.ts:66
fetch2 @ fallback.ts:108
request @ fallback.ts:142
withRetry.delay.count.count @ buildRequest.ts:69
attemptRetry @ withRetry.ts:34
retry @ withRetry.ts:30
await in retry (async)
attemptRetry @ withRetry.ts:41
await in attemptRetry (async)
(anonymous) @ withRetry.ts:45
withRetry @ withRetry.ts:24
(anonymous) @ buildRequest.ts:66
fn @ call.ts:252
exec @ createBatchScheduler.ts:54
setTimeout (async)
schedule @ createBatchScheduler.ts:95
scheduleMulticall @ call.ts:272
call @ call.ts:135
readContract @ readContract.ts:85
readContract @ public.ts:1506
readContract @ chunk-LAFZBYO7.js:2158
(anonymous) @ index.js:1076
fetchFn @ query.ts:400
run @ retryer.ts:147
createRetryer @ retryer.ts:204
fetch @ query.ts:458
executeFetch @ queryObserver.ts:350
onSubscribe @ queryObserver.ts:107
subscribe @ subscribable.ts:15
watch.immediate @ useBaseQuery.ts:88
callWithErrorHandling @ chunk-BVQHDTV7.js:1565
callWithAsyncErrorHandling @ chunk-BVQHDTV7.js:1573
job @ chunk-BVQHDTV7.js:3162
doWatch @ chunk-BVQHDTV7.js:3193
watch @ chunk-BVQHDTV7.js:3050
useBaseQuery @ useBaseQuery.ts:82
useQuery @ useQuery.ts:171
useQuery2 @ index.js:458
useContractRead @ index.js:1150
useContracts @ useContracts.ts:29
setup @ app.vue:113
callWithErrorHandling @ chunk-BVQHDTV7.js:1565
setupStatefulComponent @ chunk-BVQHDTV7.js:8631
setupComponent @ chunk-BVQHDTV7.js:8592
mountComponent @ chunk-BVQHDTV7.js:6997
hydrateNode @ chunk-BVQHDTV7.js:6026
hydrateSuspense @ chunk-BVQHDTV7.js:2953
hydrateNode @ chunk-BVQHDTV7.js:6066
hydrateSubTree @ chunk-BVQHDTV7.js:7073
componentUpdateFn @ chunk-BVQHDTV7.js:7093
run @ chunk-BVQHDTV7.js:423
instance.update @ chunk-BVQHDTV7.js:7212
setupRenderEffect @ chunk-BVQHDTV7.js:7220
mountComponent @ chunk-BVQHDTV7.js:7010
hydrateNode @ chunk-BVQHDTV7.js:6026
hydrate2 @ chunk-BVQHDTV7.js:5920
mount @ chunk-BVQHDTV7.js:5213
app.mount @ chunk-BVQHDTV7.js:10556
initApp @ entry.js:55
await in initApp (async)
(anonymous) @ entry.js:64
Show 42 more frames
Show less
localhost/:1 Access to fetch at 'https://rpc.sepolia.org/' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
chunk-BVQHDTV7.js:1565     POST https://rpc.sepolia.org/ net::ERR_FAILED 503
withTimeout.errorInstance.TimeoutError.body.body @ rpc.ts:79
(anonymous) @ withTimeout.ts:30
(anonymous) @ withTimeout.ts:37
withTimeout @ withTimeout.ts:16
http @ rpc.ts:77
fn @ http.ts:95
request @ http.ts:97
withRetry.delay.count.count @ buildRequest.ts:69
attemptRetry @ withRetry.ts:34
(anonymous) @ withRetry.ts:45
withRetry @ withRetry.ts:24
(anonymous) @ buildRequest.ts:66
fetch2 @ fallback.ts:108
request @ fallback.ts:142
withRetry.delay.count.count @ buildRequest.ts:69
attemptRetry @ withRetry.ts:34
retry @ withRetry.ts:30
await in retry (async)
attemptRetry @ withRetry.ts:41
await in attemptRetry (async)
(anonymous) @ withRetry.ts:45
withRetry @ withRetry.ts:24
(anonymous) @ buildRequest.ts:66
(anonymous) @ getBlockNumber.ts:50
withCache @ withCache.ts:55
getBlockNumber @ getBlockNumber.ts:48
getBlockNumber @ public.ts:1485
fetchBlockNumber @ chunk-LAFZBYO7.js:2637
queryFn2 @ index.js:331
fetchFn @ query.ts:400
run @ retryer.ts:147
createRetryer @ retryer.ts:204
fetch @ query.ts:458
executeFetch @ queryObserver.ts:350
onSubscribe @ queryObserver.ts:107
subscribe @ subscribable.ts:15
watch.immediate @ useBaseQuery.ts:88
callWithErrorHandling @ chunk-BVQHDTV7.js:1565
callWithAsyncErrorHandling @ chunk-BVQHDTV7.js:1573
job @ chunk-BVQHDTV7.js:3162
doWatch @ chunk-BVQHDTV7.js:3193
watch @ chunk-BVQHDTV7.js:3050
useBaseQuery @ useBaseQuery.ts:82
useQuery @ useQuery.ts:171
useQuery2 @ index.js:458
useBlockNumber @ index.js:367
useContractReads @ index.js:1237
useContracts @ useContracts.ts:36
setup @ app.vue:113
callWithErrorHandling @ chunk-BVQHDTV7.js:1565
setupStatefulComponent @ chunk-BVQHDTV7.js:8631
setupComponent @ chunk-BVQHDTV7.js:8592
mountComponent @ chunk-BVQHDTV7.js:6997
hydrateNode @ chunk-BVQHDTV7.js:6026
hydrateSuspense @ chunk-BVQHDTV7.js:2953
hydrateNode @ chunk-BVQHDTV7.js:6066
hydrateSubTree @ chunk-BVQHDTV7.js:7073
componentUpdateFn @ chunk-BVQHDTV7.js:7093
run @ chunk-BVQHDTV7.js:423
instance.update @ chunk-BVQHDTV7.js:7212
setupRenderEffect @ chunk-BVQHDTV7.js:7220
mountComponent @ chunk-BVQHDTV7.js:7010
hydrateNode @ chunk-BVQHDTV7.js:6026
hydrate2 @ chunk-BVQHDTV7.js:5920
mount @ chunk-BVQHDTV7.js:5213
app.mount @ chunk-BVQHDTV7.js:10556
initApp @ entry.js:55
await in initApp (async)
(anonymous) @ entry.js:64
Show 40 more frames
Show less
localhost/:1 Access to fetch at 'https://rpc.sepolia.org/' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
web3Connection.js:24     POST https://rpc.sepolia.org/ net::ERR_FAILED
withTimeout.errorInstance.TimeoutError.body.body @ rpc.ts:79
(anonymous) @ withTimeout.ts:30
(anonymous) @ withTimeout.ts:37
withTimeout @ withTimeout.ts:16
http @ rpc.ts:77
fn @ http.ts:95
request @ http.ts:97
withRetry.delay.count.count @ buildRequest.ts:69
attemptRetry @ withRetry.ts:34
(anonymous) @ withRetry.ts:45
withRetry @ withRetry.ts:24
(anonymous) @ buildRequest.ts:66
fetch2 @ fallback.ts:108
request @ fallback.ts:142
withRetry.delay.count.count @ buildRequest.ts:69
attemptRetry @ withRetry.ts:34
retry @ withRetry.ts:30
await in retry (async)
attemptRetry @ withRetry.ts:41
await in attemptRetry (async)
(anonymous) @ withRetry.ts:45
withRetry @ withRetry.ts:24
(anonymous) @ buildRequest.ts:66
getBalance @ getBalance.ts:68
getBalance @ public.ts:1483
fetchBalance @ chunk-LAFZBYO7.js:2414
fetchBalance @ AccountCtrl.ts:78
fetchBalance @ w3m-account-context.ts:73
Le @ w3m-account-context.ts:23
_clone @ lit-html.ts:1129
_commitTemplateResult @ lit-html.ts:1543
_$setValue @ lit-html.ts:1384
render @ lit-html.ts:2183
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
__enqueueUpdate @ reactive-element.ts:1233
await in __enqueueUpdate (async)
requestUpdate @ reactive-element.ts:1208
__initialize @ reactive-element.ts:946
ReactiveElement @ reactive-element.ts:931
LitElement @ lit-element.ts:115
jt @ index.ts:23
initUi @ client.ts:31
await in initUi (async)
c @ client.ts:25
(anonymous) @ web3Connection.js:24
(anonymous) @ client.mjs:20
executeAsync @ index.mjs:111
(anonymous) @ client.mjs:20
(anonymous) @ nuxt.js:107
fn @ nuxt.js:146
runWithContext @ chunk-BVQHDTV7.js:5256
callWithNuxt @ nuxt.js:151
runWithContext @ nuxt.js:28
applyPlugin @ nuxt.js:107
applyPlugins @ nuxt.js:119
await in applyPlugins (async)
initApp @ entry.js:47
(anonymous) @ entry.js:64
Show 43 more frames
Show less
localhost/:1 Access to fetch at 'https://rpc.sepolia.org/' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
chunk-BVQHDTV7.js:1565     POST https://rpc.sepolia.org/ net::ERR_FAILED 503
withTimeout.errorInstance.TimeoutError.body.body @ rpc.ts:79
(anonymous) @ withTimeout.ts:30
(anonymous) @ withTimeout.ts:37
withTimeout @ withTimeout.ts:16
http @ rpc.ts:77
fn @ http.ts:95
request @ http.ts:97
withRetry.delay.count.count @ buildRequest.ts:69
attemptRetry @ withRetry.ts:34
(anonymous) @ withRetry.ts:45
withRetry @ withRetry.ts:24
(anonymous) @ buildRequest.ts:66
fetch2 @ fallback.ts:108
request @ fallback.ts:142
withRetry.delay.count.count @ buildRequest.ts:69
attemptRetry @ withRetry.ts:34
retry @ withRetry.ts:30
await in retry (async)
attemptRetry @ withRetry.ts:41
await in attemptRetry (async)
retry @ withRetry.ts:30
await in retry (async)
attemptRetry @ withRetry.ts:41
await in attemptRetry (async)
(anonymous) @ withRetry.ts:45
withRetry @ withRetry.ts:24
(anonymous) @ buildRequest.ts:66
call @ call.ts:149
readContract @ readContract.ts:85
(anonymous) @ multicall.ts:177
multicall @ multicall.ts:176
multicall @ public.ts:1505
multicall @ chunk-LAFZBYO7.js:2138
(anonymous) @ chunk-LAFZBYO7.js:2188
promises @ chunk-LAFZBYO7.js:2187
readContracts @ chunk-LAFZBYO7.js:2198
(anonymous) @ index.js:1208
fetchFn @ query.ts:400
run @ retryer.ts:147
createRetryer @ retryer.ts:204
fetch @ query.ts:458
executeFetch @ queryObserver.ts:350
onSubscribe @ queryObserver.ts:107
subscribe @ subscribable.ts:15
watch.immediate @ useBaseQuery.ts:88
callWithErrorHandling @ chunk-BVQHDTV7.js:1565
callWithAsyncErrorHandling @ chunk-BVQHDTV7.js:1573
job @ chunk-BVQHDTV7.js:3162
doWatch @ chunk-BVQHDTV7.js:3193
watch @ chunk-BVQHDTV7.js:3050
useBaseQuery @ useBaseQuery.ts:82
useQuery @ useQuery.ts:171
useQuery2 @ index.js:458
useContractReads @ index.js:1270
useContracts @ useContracts.ts:36
setup @ app.vue:113
callWithErrorHandling @ chunk-BVQHDTV7.js:1565
setupStatefulComponent @ chunk-BVQHDTV7.js:8631
setupComponent @ chunk-BVQHDTV7.js:8592
mountComponent @ chunk-BVQHDTV7.js:6997
hydrateNode @ chunk-BVQHDTV7.js:6026
hydrateSuspense @ chunk-BVQHDTV7.js:2953
hydrateNode @ chunk-BVQHDTV7.js:6066
hydrateSubTree @ chunk-BVQHDTV7.js:7073
componentUpdateFn @ chunk-BVQHDTV7.js:7093
run @ chunk-BVQHDTV7.js:423
instance.update @ chunk-BVQHDTV7.js:7212
setupRenderEffect @ chunk-BVQHDTV7.js:7220
mountComponent @ chunk-BVQHDTV7.js:7010
hydrateNode @ chunk-BVQHDTV7.js:6026
hydrate2 @ chunk-BVQHDTV7.js:5920
mount @ chunk-BVQHDTV7.js:5213
app.mount @ chunk-BVQHDTV7.js:10556
initApp @ entry.js:55
await in initApp (async)
(anonymous) @ entry.js:64
Show 45 more frames
Show less
localhost/:1 Access to fetch at 'https://rpc.sepolia.org/' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
chunk-BVQHDTV7.js:1565     POST https://rpc.sepolia.org/ net::ERR_FAILED 503
withTimeout.errorInstance.TimeoutError.body.body @ rpc.ts:79
(anonymous) @ withTimeout.ts:30
(anonymous) @ withTimeout.ts:37
withTimeout @ withTimeout.ts:16
http @ rpc.ts:77
fn @ http.ts:95
request @ http.ts:97
withRetry.delay.count.count @ buildRequest.ts:69
attemptRetry @ withRetry.ts:34
(anonymous) @ withRetry.ts:45
withRetry @ withRetry.ts:24
(anonymous) @ buildRequest.ts:66
fetch2 @ fallback.ts:108
request @ fallback.ts:142
withRetry.delay.count.count @ buildRequest.ts:69
attemptRetry @ withRetry.ts:34
retry @ withRetry.ts:30
await in retry (async)
attemptRetry @ withRetry.ts:41
await in attemptRetry (async)
retry @ withRetry.ts:30
await in retry (async)
attemptRetry @ withRetry.ts:41
await in attemptRetry (async)
(anonymous) @ withRetry.ts:45
withRetry @ withRetry.ts:24
(anonymous) @ buildRequest.ts:66
(anonymous) @ getBlockNumber.ts:50
withCache @ withCache.ts:55
getBlockNumber @ getBlockNumber.ts:48
getBlockNumber @ public.ts:1485
fetchBlockNumber @ chunk-LAFZBYO7.js:2637
queryFn2 @ index.js:331
fetchFn @ query.ts:400
run @ retryer.ts:147
createRetryer @ retryer.ts:204
fetch @ query.ts:458
executeFetch @ queryObserver.ts:350
onSubscribe @ queryObserver.ts:107
subscribe @ subscribable.ts:15
watch.immediate @ useBaseQuery.ts:88
callWithErrorHandling @ chunk-BVQHDTV7.js:1565
callWithAsyncErrorHandling @ chunk-BVQHDTV7.js:1573
job @ chunk-BVQHDTV7.js:3162
doWatch @ chunk-BVQHDTV7.js:3193
watch @ chunk-BVQHDTV7.js:3050
useBaseQuery @ useBaseQuery.ts:82
useQuery @ useQuery.ts:171
useQuery2 @ index.js:458
useBlockNumber @ index.js:367
useContractReads @ index.js:1237
useContracts @ useContracts.ts:36
setup @ app.vue:113
callWithErrorHandling @ chunk-BVQHDTV7.js:1565
setupStatefulComponent @ chunk-BVQHDTV7.js:8631
setupComponent @ chunk-BVQHDTV7.js:8592
mountComponent @ chunk-BVQHDTV7.js:6997
hydrateNode @ chunk-BVQHDTV7.js:6026
hydrateSuspense @ chunk-BVQHDTV7.js:2953
hydrateNode @ chunk-BVQHDTV7.js:6066
hydrateSubTree @ chunk-BVQHDTV7.js:7073
componentUpdateFn @ chunk-BVQHDTV7.js:7093
run @ chunk-BVQHDTV7.js:423
instance.update @ chunk-BVQHDTV7.js:7212
setupRenderEffect @ chunk-BVQHDTV7.js:7220
mountComponent @ chunk-BVQHDTV7.js:7010
hydrateNode @ chunk-BVQHDTV7.js:6026
hydrate2 @ chunk-BVQHDTV7.js:5920
mount @ chunk-BVQHDTV7.js:5213
app.mount @ chunk-BVQHDTV7.js:10556
initApp @ entry.js:55
await in initApp (async)
(anonymous) @ entry.js:64
Show 42 more frames
Show less
localhost/:1 Access to fetch at 'https://rpc.sepolia.org/' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
web3Connection.js:24     POST https://rpc.sepolia.org/ net::ERR_FAILED 503
withTimeout.errorInstance.TimeoutError.body.body @ rpc.ts:79
(anonymous) @ withTimeout.ts:30
(anonymous) @ withTimeout.ts:37
withTimeout @ withTimeout.ts:16
http @ rpc.ts:77
fn @ http.ts:95
request @ http.ts:97
withRetry.delay.count.count @ buildRequest.ts:69
attemptRetry @ withRetry.ts:34
(anonymous) @ withRetry.ts:45
withRetry @ withRetry.ts:24
(anonymous) @ buildRequest.ts:66
fetch2 @ fallback.ts:108
request @ fallback.ts:142
withRetry.delay.count.count @ buildRequest.ts:69
attemptRetry @ withRetry.ts:34
retry @ withRetry.ts:30
await in retry (async)
attemptRetry @ withRetry.ts:41
await in attemptRetry (async)
retry @ withRetry.ts:30
await in retry (async)
attemptRetry @ withRetry.ts:41
await in attemptRetry (async)
(anonymous) @ withRetry.ts:45
withRetry @ withRetry.ts:24
(anonymous) @ buildRequest.ts:66
getBalance @ getBalance.ts:68
getBalance @ public.ts:1483
fetchBalance @ chunk-LAFZBYO7.js:2414
fetchBalance @ AccountCtrl.ts:78
fetchBalance @ w3m-account-context.ts:73
Le @ w3m-account-context.ts:23
_clone @ lit-html.ts:1129
_commitTemplateResult @ lit-html.ts:1543
_$setValue @ lit-html.ts:1384
render @ lit-html.ts:2183
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
__enqueueUpdate @ reactive-element.ts:1233
await in __enqueueUpdate (async)
requestUpdate @ reactive-element.ts:1208
__initialize @ reactive-element.ts:946
ReactiveElement @ reactive-element.ts:931
LitElement @ lit-element.ts:115
jt @ index.ts:23
initUi @ client.ts:31
await in initUi (async)
c @ client.ts:25
(anonymous) @ web3Connection.js:24
(anonymous) @ client.mjs:20
executeAsync @ index.mjs:111
(anonymous) @ client.mjs:20
(anonymous) @ nuxt.js:107
fn @ nuxt.js:146
runWithContext @ chunk-BVQHDTV7.js:5256
callWithNuxt @ nuxt.js:151
runWithContext @ nuxt.js:28
applyPlugin @ nuxt.js:107
applyPlugins @ nuxt.js:119
await in applyPlugins (async)
initApp @ entry.js:47
(anonymous) @ entry.js:64
Show 45 more frames
Show less
localhost/:1 Access to fetch at 'https://rpc.sepolia.org/' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
web3Connection.js:24     POST https://rpc.sepolia.org/ net::ERR_FAILED 503
withTimeout.errorInstance.TimeoutError.body.body @ rpc.ts:79
(anonymous) @ withTimeout.ts:30
(anonymous) @ withTimeout.ts:37
withTimeout @ withTimeout.ts:16
http @ rpc.ts:77
fn @ http.ts:95
request @ http.ts:97
withRetry.delay.count.count @ buildRequest.ts:69
attemptRetry @ withRetry.ts:34
(anonymous) @ withRetry.ts:45
withRetry @ withRetry.ts:24
(anonymous) @ buildRequest.ts:66
fetch2 @ fallback.ts:108
request @ fallback.ts:142
withRetry.delay.count.count @ buildRequest.ts:69
attemptRetry @ withRetry.ts:34
retry @ withRetry.ts:30
await in retry (async)
attemptRetry @ withRetry.ts:41
await in attemptRetry (async)
retry @ withRetry.ts:30
await in retry (async)
attemptRetry @ withRetry.ts:41
await in attemptRetry (async)
retry @ withRetry.ts:30
await in retry (async)
attemptRetry @ withRetry.ts:41
await in attemptRetry (async)
(anonymous) @ withRetry.ts:45
withRetry @ withRetry.ts:24
(anonymous) @ buildRequest.ts:66
getBalance @ getBalance.ts:68
getBalance @ public.ts:1483
fetchBalance @ chunk-LAFZBYO7.js:2414
fetchBalance @ AccountCtrl.ts:78
fetchBalance @ w3m-account-context.ts:73
Le @ w3m-account-context.ts:23
_clone @ lit-html.ts:1129
_commitTemplateResult @ lit-html.ts:1543
_$setValue @ lit-html.ts:1384
render @ lit-html.ts:2183
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
__enqueueUpdate @ reactive-element.ts:1233
await in __enqueueUpdate (async)
requestUpdate @ reactive-element.ts:1208
__initialize @ reactive-element.ts:946
ReactiveElement @ reactive-element.ts:931
LitElement @ lit-element.ts:115
jt @ index.ts:23
initUi @ client.ts:31
await in initUi (async)
c @ client.ts:25
(anonymous) @ web3Connection.js:24
(anonymous) @ client.mjs:20
executeAsync @ index.mjs:111
(anonymous) @ client.mjs:20
(anonymous) @ nuxt.js:107
fn @ nuxt.js:146
runWithContext @ chunk-BVQHDTV7.js:5256
callWithNuxt @ nuxt.js:151
runWithContext @ nuxt.js:28
applyPlugin @ nuxt.js:107
applyPlugins @ nuxt.js:119
await in applyPlugins (async)
initApp @ entry.js:47
(anonymous) @ entry.js:64
Show 47 more frames
Show less
web3Connection.js:24 HttpRequestError: HTTP request failed.

URL: https://rpc.sepolia.org
Request body: {"method":"eth_getBalance","params":["0x0A49c25Ed8fb99C06527EDB99E61E155F2C8d674","latest"]}

Details: Failed to fetch
Version: viem@1.5.3
    at Object.http (rpc.ts:127:11)
    at async fn (http.ts:95:18)
    at async request (http.ts:97:39)
    at async withRetry.delay.count.count (buildRequest.ts:69:18)
    at async attemptRetry (withRetry.ts:34:22)
fetchBalance @ w3m-account-context.ts:75
await in fetchBalance (async)
Le @ w3m-account-context.ts:23
_clone @ lit-html.ts:1129
_commitTemplateResult @ lit-html.ts:1543
_$setValue @ lit-html.ts:1384
render @ lit-html.ts:2183
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
__enqueueUpdate @ reactive-element.ts:1233
await in __enqueueUpdate (async)
requestUpdate @ reactive-element.ts:1208
__initialize @ reactive-element.ts:946
ReactiveElement @ reactive-element.ts:931
LitElement @ lit-element.ts:115
jt @ index.ts:23
initUi @ client.ts:31
await in initUi (async)
c @ client.ts:25
(anonymous) @ web3Connection.js:24
(anonymous) @ client.mjs:20
executeAsync @ index.mjs:111
(anonymous) @ client.mjs:20
(anonymous) @ nuxt.js:107
fn @ nuxt.js:146
runWithContext @ chunk-BVQHDTV7.js:5256
callWithNuxt @ nuxt.js:151
runWithContext @ nuxt.js:28
applyPlugin @ nuxt.js:107
applyPlugins @ nuxt.js:119
await in applyPlugins (async)
initApp @ entry.js:47
(anonymous) @ entry.js:64
Show 18 more frames
Show less
```

**Comment by unicape** [comment]
@dataexcess Please provide a reproducible use case

**Comment by unicape** [comment]
long time no reply close
